Repository Dev-FE-3/toy-project2-team3, pull requests merged in 2025-02, with the labels that each got.

#2 [공통 컴포넌트]드롭다운 추가 #1
  .gitignore
  .prettierrc
  eslint.config.js
  package-lock.json
  package.json
  server.js
  src/App.tsx
  src/declarations.d.ts
  src/fireBase.tsx
  src/index.css
  src/main.tsx
  src/pages/calendar/CalendarCell.tsx
  src/pages/calendar/CalendarHeader.tsx
  src/pages/calendar/CalendarMain.tsx
  src/pages/calendar/CalendarModal.tsx
  src/widgets/dropdown/Dropdown.tsx
  src/widgets/dropdown/DropdownSample.tsx
  tsconfig.json
  tsconfig.node.json
  vite.config.js
Labels: ✨ Feature

#14 Feat: 로그인 페이지
  package-lock.json
  package.json
  src/fireBase.tsx
  src/pages/login/index.tsx
  src/pages/login/style.tsx
Labels: ✨ Feature, 🎨 Html & css

#23 Feature : 마이페이지 퍼블리싱
  index.html
  package-lock.json
  src/App.css
  src/assets/images/profile-default.png
  src/pages/mypage/index.tsx
  src/pages/mypage/styles/mypage.styles.ts
  src/pages/mypage/styles/salary-modal.styles.ts
  src/pages/mypage/styles/salary-section.styles.ts
  src/pages/mypage/styles/user-section.styles.ts
  src/pages/mypage/ui/salary-modal.tsx
  src/pages/mypage/ui/salary-section.tsx
  src/pages/mypage/ui/user-section.tsx
  src/shared/button/Button.tsx
  src/shared/dropdown/Dropdown.tsx
Labels: 🎨 Html & css
