Repository Dev-FE-3/toy-project2-team3, pull requests merged in 2025-03, with the labels that each got.

#33 Refactor : 로그인 로직 커스텀 훅으로 분리
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/images/devHR_logo.png
  src/assets/imgs/signup_graphic.svg
  src/features/auth/useLogin.ts
  src/main.tsx
  src/pages/login/index.tsx
  src/pages/login/style.ts
  src/pages/signup/index.tsx
  src/pages/signup/style.ts
  src/styles/createGlobalStyle.ts
Labels: ✨ Feature, 🎨 Html & css, 🔨 Refactor

#35 Feat : 로그아웃 기능 구현
  src/features/navbar/index.tsx
Labels: ✨ Feature

#43 Design : 404 페이지 퍼블리싱
  src/assets/images/curation.svg
  src/global.d.ts
  src/pages/not-found/index.tsx
Labels: 🎨 Html & css

#44 Feat : PublicRoute type 추가 (이미 로그인한 사용자가 /login, /signup 페이지에 접근하는 것 제한)
  src/features/auth/AuthRoute.tsx
  src/providers/RouterProvider.tsx
Labels: ✨ Feature

#40 Feat : 일정 관리 모달 제목 달력에 연동
  src/pages/calendar/styles/calendar-cell.styles.ts
  src/pages/calendar/styles/calendar-header.styles.ts
  src/pages/calendar/styles/calendar-main.styles.ts
  src/pages/calendar/styles/calendar-modal.style.ts
  src/pages/calendar/styles/confirmation-modal.style.ts
  src/pages/calendar/ui/calendar-cell.tsx
  src/pages/calendar/ui/calendar-header.tsx
  src/pages/calendar/ui/calendar-main.tsx
  src/pages/calendar/ui/calendar-modal.tsx
  src/pages/calendar/ui/confirmation-modal.tsx
  src/pages/work-calendar/index.tsx
  src/shared/dropdown/Dropdown.tsx
Labels: ✨ Feature

#48 Feat : 로그인/로그아웃 성공 시 toast 메세지 출력
  package-lock.json
  package.json
  src/assets/images/devHR_logo.png
  src/features/auth/useLogin.ts
  src/features/navbar/index.tsx
  src/main.tsx
Labels: ✨ Feature

#52 Feat: 일정 관리 페이지 파이어 베이스 연동
  src/pages/calendar/styles/calendar-cell.styles.ts
  src/pages/calendar/styles/calendar-main.styles.ts
  src/pages/calendar/ui/calendar-cell.tsx
  src/pages/calendar/ui/calendar-main.tsx
  src/pages/calendar/ui/calendar-modal.tsx
  src/shared/dropdown/Dropdown.tsx
Labels: ✨ Feature

#60 Feat : 로그아웃 확인 모달 추가
  src/assets/images/devHR_logo.png
  src/features/navbar/index.tsx
Labels: ✨ Feature

#61 Feat : 회원가입 성공 시 toast 메세지 출력
  src/features/auth/useSignUp.ts
Labels: ✨ Feature

#50 Feat: 마이 페이지 기능 구현 및 Redux를 활용한 급여 내역 관리
  package-lock.json
  package.json
  src/assets/Images/profile-default.png
  src/assets/Images/profile-default.svg
  src/assets/images/devHR_logo.png
  src/assets/images/profile-default.png
  src/features/mypage/index.tsx
  src/main.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/styles/mypage.styles.ts
  src/pages/mypage/styles/salary-modal.styles.ts
  src/pages/mypage/styles/salary-section.styles.ts
  src/pages/mypage/styles/user-section.styles.ts
  src/pages/mypage/ui/salary-modal.tsx
  src/pages/mypage/ui/salary-section.tsx
  src/pages/mypage/ui/user-section.tsx
  src/redux/salary-slice.ts
  src/redux/store.ts
  src/shared/button/Button.tsx
  src/shared/dropdown/Dropdown.tsx
  src/styles/createGlobalStyle.ts
Labels: ✨ Feature

#69 Feat: MyPage 프로필 이미지 업로드 방식 변경
  src/pages/mypage/index.tsx
  src/pages/mypage/styles/mypage.styles.ts
  src/pages/mypage/styles/salary-section.styles.ts
  src/pages/mypage/ui/salary-modal.tsx
  src/pages/mypage/ui/salary-section.tsx
  src/pages/mypage/ui/user-section.tsx
  src/pages/mypage/useFetchSalaryData.ts
  src/pages/mypage/useFetchUserData.ts
  src/styles/createGlobalStyle.ts
  src/utils/formatCurrency.ts
  src/utils/formatDate.ts
Labels: ✨ Feature, 🔨 Refactor

#71 [Feat] 일정 관리 페이지 일정 띠 개선, 드롭다운 컴포넌트 2가지 버전 개발.
  src/features/work-calendar/styles/calendar-cell.styles.ts
  src/features/work-calendar/styles/calendar-header.styles.ts
  src/features/work-calendar/styles/calendar-modal.style.ts
  src/features/work-calendar/styles/confirmation-modal.style.ts
  src/features/work-calendar/styles/event-list-modal.styles.ts
  src/features/work-calendar/ui/calendar-header.tsx
  src/features/work-calendar/ui/calendar-main.tsx
  src/features/work-calendar/ui/calendar-modal.tsx
  src/features/work-calendar/ui/event-list-modal.tsx
  src/shared/dropdown/Dropdown.tsx
  src/shared/dropdown/DropdownSample.tsx
Labels: ✨ Feature

#73 Feat : 급여 내역이 없는 경우의 드롭다운 존재 X, 메세지 추가
  src/pages/mypage/styles/mypage.styles.ts
  src/pages/mypage/styles/salary-section.styles.ts
  src/pages/mypage/ui/salary-section.tsx
Labels: ✨ Feature

#84 Feat : 회원가입 시에 급여 내역 정보 기본값 저장
  src/features/auth/useSignUp.ts
  src/pages/signup/index.tsx
Labels: ✨ Feature, 🔨 Refactor

#85 Feat : 404 페이지 내 홈으로 이동하는 Link 추가
  src/pages/not-found/index.tsx
Labels: ✨ Feature

#87 Refactor : salary correction
  src/App.css
  src/App.tsx
  src/pages/salary-correction/index.tsx
  src/providers/RouterProvider.tsx
  src/shared/button/Button.tsx
Labels: 🔨 Refactor

#89 Refactor : 마이페이지 리팩토링
  package-lock.json
  package.json
  src/assets/images/edit_icon.svg
  src/features/mypage/hooks/useFetchSalaryData.ts
  src/features/mypage/hooks/useFetchUserData.ts
  src/features/mypage/styles/salary-modal.styles.ts
  src/features/mypage/styles/salary-section.styles.ts
  src/features/mypage/styles/user-section.styles.ts
  src/features/mypage/types/salaryTypes.ts
  src/features/mypage/ui/salary-modal.tsx
  src/features/mypage/ui/salary-section.tsx
  src/features/mypage/ui/user-section.tsx
  src/features/mypage/utils/formatCurrency.ts
  src/features/mypage/utils/formatDate.ts
  src/pages/mypage/index.tsx
  src/pages/mypage/styles.ts
  src/pages/mypage/useFetchSalaryData.ts
  src/pages/mypage/useFetchUserData.ts
  src/pages/salary-correction/index.tsx
  src/styles/createGlobalStyle.ts
  src/utils/formatDate.ts
Labels: 🔨 Refactor

#88 Refactor : 로그인/회원가입 관련 리팩토링
  src/features/auth/hooks/useLogin.ts
  src/features/auth/hooks/useSignUp.ts
  src/features/auth/useLogin.ts
  src/features/auth/useSignUp.ts
  src/features/auth/utils/firestoreHelpers.ts
  src/features/navbar/index.tsx
  src/main.tsx
  src/pages/login/index.tsx
  src/pages/login/style.ts
  src/pages/signup/index.tsx
  src/shared/modal/Modal.tsx
  src/shared/utils/firebaseErrorHandler.ts
Labels: 🔨 Refactor

#92 Refactor : 일정 관리 페이지 리펙토링
  README.md
  backup-files/index.tsx
  package-lock.json
  src/features/work-calendar/styles/calendar-cell.styles.ts
  src/features/work-calendar/styles/calendar-main.styles.ts
  src/features/work-calendar/styles/calendar-modal.style.ts
  src/features/work-calendar/styles/confirmation-modal.style.ts
  src/features/work-calendar/ui/calendar-cell.tsx
  src/features/work-calendar/ui/calendar-firebase-service.tsx
  src/features/work-calendar/ui/calendar-header.tsx
  src/features/work-calendar/ui/calendar-main.tsx
  src/features/work-calendar/ui/calendar-modal.tsx
  src/features/work-calendar/ui/calendar-utils.tsx
  src/features/work-calendar/ui/calendar-utils/calendar-utils.tsx
  src/features/work-calendar/ui/confirmation-modal.tsx
  src/features/work-calendar/ui/event-list-modal.tsx
  src/pages/salary-correction/index.tsx
  src/pages/work-calendar/index.tsx
  src/shared/dropdown/Dropdown.tsx
  src/shared/dropdown/index.ts
Labels: 🔨 Refactor
